function shopeeSearch(keyword) {
  return `https://shopee.co.th/search?keyword=${encodeURIComponent(keyword)}`;
}

const productCatalog = [
  {
    id: "tea-gift-set",
    title: "เซ็ตชา 3 รส",
    icon: "🍵",
    recipients: ["friend", "family", "coworker"],
    genders: ["unisex"],
    ageRange: [18, 75],
    occasions: ["birthday", "thankyou", "festival"],
    personality: ["foodie", "homebody", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–700 บาท",
    currentPrice: "฿269 - ฿449",
    text: "ของขวัญสุภาพ ให้ได้ทั้งเพื่อนร่วมงาน ผู้ใหญ่ และคนที่ชอบจิบอะไรอุ่น ๆ",
    color: "#bcebd7",
    imageUrl: "https://down-th.img.susercontent.com/file/th-11134207-81ztj-mnzsjh53whl2ce.webp",
    researchUrl:
      "https://shopee.co.th/%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D-%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%8A%E0%B8%B2-3-%E0%B8%8A%E0%B8%99%E0%B8%B4%E0%B8%94-%E0%B8%88%E0%B8%B2%E0%B8%81%E0%B9%81%E0%B8%9A%E0%B8%A3%E0%B8%99%E0%B8%94%E0%B9%8C-guru-tea-%E0%B8%8A%E0%B8%B2%E0%B8%A1%E0%B8%B0%E0%B8%A5%E0%B8%B4-%E0%B8%8A%E0%B8%B2%E0%B8%A2%E0%B8%AD%E0%B8%94%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%84%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9C%E0%B8%B6%E0%B9%89%E0%B8%87-%E0%B8%8A%E0%B8%B2%E0%B8%AB%E0%B8%AD%E0%B8%A1%E0%B8%AB%E0%B8%A1%E0%B8%B7%E0%B9%88%E0%B8%99%E0%B8%A5%E0%B8%B5%E0%B9%89-%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%82%E0%B8%B2%E0%B8%A2%E0%B8%94%E0%B8%B5-i.25099264.54508225154",
    affiliateUrl: "https://s.shopee.co.th/AKYQAVjVBI",
  },
  {
    id: "premium-snack-box",
    title: "กล่องขนมหรือถั่วพรีเมียม",
    icon: "🥜",
    recipients: ["friend", "family", "coworker"],
    genders: ["unisex"],
    ageRange: [18, 75],
    occasions: ["festival", "thankyou", "birthday"],
    personality: ["foodie", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–900 บาท",
    currentPrice: "฿389",
    text: "หยิบกินง่าย แพ็กสวย เหมาะกับเทศกาลและการฝากผู้ใหญ่แบบไม่เสี่ยงเกินไป",
    color: "#ffd8a8",
    imageUrl: "https://down-th.img.susercontent.com/file/dce6a2ab81ebddc0c1926db5fd6e6f80_tn",
    researchUrl:
      "https://shopee.co.th/Gift-Set-%E0%B8%81%E0%B8%A5%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D-%E0%B9%80%E0%B8%8B%E0%B8%95-%E0%B8%AD%E0%B8%B1%E0%B8%A5%E0%B8%A1%E0%B8%AD%E0%B8%99%E0%B8%94%E0%B9%8C%E0%B8%9C%E0%B8%AA%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B9%87%E0%B8%94%E0%B8%A1%E0%B8%B0%E0%B8%A1%E0%B9%88%E0%B8%A7%E0%B8%87-i.304134090.7269177443",
    affiliateUrl: "https://s.shopee.co.th/BRe3srmlB",
  },
  {
    id: "body-care-set",
    title: "เซ็ตดูแลผิวและผม",
    icon: "🧴",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["female"],
    ageRange: [18, 55],
    occasions: ["birthday", "festival", "anniversary", "justbecause"],
    personality: ["homebody", "practical", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 800–2,500 บาท",
    currentPrice: "฿1,810",
    text: "ของใช้ได้จริงแต่ยังดูพิเศษ เลือกกลิ่นสะอาด ๆ จะให้ได้ง่ายกว่า",
    color: "#e8c8e8",
    imageUrl: "https://down-th.img.susercontent.com/file/th-11134207-81ztm-mop562k2a9e661_tn",
    researchUrl:
      "https://shopee.co.th/Kaff-Co.-Holiday-Set-1-2-Holiday-Hair-Skin-Care-%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D%E0%B9%81%E0%B8%AB%E0%B9%88%E0%B8%87%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B9%E0%B9%81%E0%B8%A5%E0%B8%84%E0%B8%A3%E0%B8%9A%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3-i.314209019.13156093664",
    affiliateUrl: "https://s.shopee.co.th/3B5FdQiAY1",
  },
  {
    id: "business-gift-set",
    title: "เซ็ตแก้วเก็บความร้อนและร่ม",
    icon: "☂️",
    recipients: ["coworker", "family"],
    genders: ["unisex"],
    ageRange: [22, 65],
    occasions: ["thankyou", "festival", "celebrate"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–900 บาท",
    currentPrice: "฿224",
    text: "ดูสุภาพ ใช้งานได้จริง เหมาะกับลูกค้า เพื่อนร่วมงาน หรือจับฉลากออฟฟิศ",
    color: "#abc9ff",
    imageUrl: "assets/product-images/business-gift-set.jpg",
    researchUrl:
      "https://shopee.co.th/%F0%9F%8E%81-Gift-Set-%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D%E0%B8%98%E0%B8%B8%E0%B8%A3%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A2%E0%B8%B8%E0%B8%81%E0%B8%95%E0%B9%8C%E0%B9%83%E0%B8%8A%E0%B9%89-%E0%B9%81%E0%B8%81%E0%B9%89%E0%B8%A7%E0%B9%80%E0%B8%81%E0%B9%87%E0%B8%9A%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%99-%E0%B8%A3%E0%B9%88%E0%B8%A1-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%9E%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%87%E0%B8%B2%E0%B8%99-%E0%B8%A5%E0%B8%B9%E0%B8%81%E0%B8%84%E0%B9%89%E0%B8%B2-%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%9B%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B8%B1%E0%B8%A7-%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B9%80%E0%B8%81%E0%B8%B4%E0%B8%94-fan-i.877179409.56806485159",
    affiliateUrl: "https://s.shopee.co.th/1Vx1h8dbeK",
  },
  {
    id: "aroma-diffuser",
    title: "ดิฟฟิวเซอร์หรือเทียนหอม",
    icon: "🕯️",
    recipients: ["friend", "partner", "family", "self"],
    occasions: ["birthday", "thankyou", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium", "large"],
    price: "ประมาณ 250–1,800 บาท",
    text: "ช่วยให้ห้องน่าอยู่ขึ้น เหมาะกับคนรักบ้าน โต๊ะทำงาน หรือของขวัญขึ้นบ้านใหม่",
    color: "#ffb2c7",
    imageUrl: "",
    researchUrl: shopeeSearch("ดิฟฟิวเซอร์ เทียนหอม ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "board-game",
    title: "บอร์ดเกมเล่นง่าย",
    icon: "🎲",
    recipients: ["friend", "partner", "kid", "self"],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–1,500 บาท",
    text: "เหมาะกับคนชอบชวนเพื่อนเล่น เลือกเกมที่กติกาไม่ยากและเล่นซ้ำได้",
    color: "#ffce4d",
    imageUrl: "",
    researchUrl: shopeeSearch("บอร์ดเกม ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "wireless-earbuds",
    title: "หูฟังไร้สาย",
    icon: "🎧",
    recipients: ["friend", "partner", "family", "self"],
    occasions: ["birthday", "celebrate", "anniversary"],
    personality: ["tech", "active", "practical"],
    budget: ["medium", "large", "premium"],
    price: "ประมาณ 900–5,000 บาท",
    text: "ใช้ได้ทุกวันทั้งเดินทาง ทำงาน และออกกำลัง เป็นของที่คนรับนึกถึงบ่อย",
    color: "#b8c5ff",
    imageUrl: "",
    researchUrl: shopeeSearch("หูฟังไร้สาย ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "instant-camera",
    title: "กล้องอินสแตนท์หรือเครื่องพิมพ์รูป",
    icon: "📸",
    recipients: ["partner", "friend", "self"],
    occasions: ["birthday", "anniversary", "celebrate"],
    personality: ["creative", "active", "tech"],
    budget: ["large", "premium"],
    price: "ประมาณ 2,000–6,500 บาท",
    text: "เหมาะกับคนชอบถ่ายรูป เที่ยว และเก็บความทรงจำให้จับต้องได้",
    color: "#f4a8a1",
    imageUrl: "",
    researchUrl: shopeeSearch("กล้อง instant camera ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "travel-organizer",
    title: "กระเป๋าจัดระเบียบเดินทาง",
    icon: "🧳",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    occasions: ["birthday", "celebrate", "festival", "thankyou"],
    personality: ["active", "practical", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 200–1,200 บาท",
    text: "ของใช้จริงที่ช่วยชีวิตคนเดินทางบ่อย จัดสายชาร์จ เครื่องสำอาง หรือเสื้อผ้าได้",
    color: "#9fd9ef",
    imageUrl: "",
    researchUrl: shopeeSearch("กระเป๋าจัดระเบียบเดินทาง ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "plant-pot",
    title: "ต้นไม้ดูแลง่ายพร้อมกระถาง",
    icon: "🪴",
    recipients: ["friend", "family", "coworker", "self"],
    occasions: ["thankyou", "celebrate", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 150–900 บาท",
    text: "เหมาะกับโต๊ะทำงาน บ้านใหม่ หรือคนที่อยากเพิ่มสีเขียวแต่ไม่มีเวลาดูแลมาก",
    color: "#a9dfb3",
    imageUrl: "",
    researchUrl: shopeeSearch("ต้นไม้ดูแลง่าย กระถาง ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "baby-gift-set",
    title: "เซ็ตของขวัญเด็กแรกเกิด",
    icon: "🍼",
    recipients: ["kid", "family"],
    occasions: ["thankyou", "celebrate", "festival"],
    personality: ["practical"],
    budget: ["small", "medium", "large"],
    price: "ประมาณ 300–2,000 บาท",
    text: "ใช้ได้จริงและดูอบอุ่น เหมาะกับเยี่ยมคลอด รับขวัญหลาน หรือฝากครอบครัว",
    color: "#f8c986",
    imageUrl: "",
    researchUrl: shopeeSearch("เซ็ตของขวัญเด็กแรกเกิด"),
    affiliateUrl: "",
  },
  {
    id: "cookware",
    title: "เครื่องครัวชิ้นเก่ง",
    icon: "🍳",
    recipients: ["family", "friend", "partner", "self"],
    occasions: ["birthday", "celebrate", "thankyou", "anniversary"],
    personality: ["foodie", "practical", "homebody"],
    budget: ["medium", "large", "premium"],
    price: "ประมาณ 700–5,000 บาท",
    text: "เหมาะกับคนชอบทำอาหาร เลือกแบรนด์ดี ๆ แล้วเขาจะหยิบใช้ได้นาน",
    color: "#ffc6a5",
    imageUrl: "",
    researchUrl: shopeeSearch("เครื่องครัว ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "mens-loafer-shoes",
    title: "รองเท้าโลฟเฟอร์ผู้ชาย",
    icon: "👞",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [20, 60],
    occasions: ["birthday", "anniversary", "celebrate", "justbecause"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–900 บาท",
    currentPrice: "฿488",
    text: "รองเท้าทรงสุภาพใส่ได้หลายโอกาส เหมาะกับผู้ชายที่ชอบของใช้จริงและแต่งตัวง่าย",
    color: "#d9c2a3",
    imageUrl: "assets/product-images/mens-loafer-shoes.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6L2HUJ8Fuf",
  },
  {
    id: "mens-bomber-jacket",
    title: "แจ็กเก็ตผู้ชายทรงคลาสสิก",
    icon: "🧥",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [18, 55],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–900 บาท",
    currentPrice: "฿432",
    text: "แจ็กเก็ตทรงเรียบใส่ง่าย เหมาะกับผู้ชายที่ชอบเสื้อผ้าใช้งานได้หลายสถานการณ์",
    color: "#2f3136",
    imageUrl: "assets/product-images/mens-bomber-jacket.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/40eMiAKeUU",
  },
  {
    id: "cheese-mini-gift",
    title: "กล่องของขวัญธีมชีสน่ารัก",
    icon: "🧀",
    recipients: ["friend", "kid", "coworker", "self"],
    genders: ["unisex"],
    ageRange: [8, 35],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small"],
    price: "ประมาณ 50–150 บาท",
    currentPrice: "฿69",
    text: "ของขวัญชิ้นเล็กหน้าตาน่ารัก เหมาะกับจับฉลาก เพื่อนสนิท หรือของแถมให้ดูใส่ใจ",
    color: "#ffce4d",
    imageUrl: "assets/product-images/cheese-mini-gift.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7fXf5A1T3T",
  },
  {
    id: "goose-plush-pillow",
    title: "ตุ๊กตาห่านกอดนุ่ม",
    icon: "🪿",
    recipients: ["partner", "friend", "kid", "self"],
    genders: ["female"],
    ageRange: [6, 35],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 90–300 บาท",
    currentPrice: "฿93",
    text: "ตุ๊กตากอดนุ่มชิ้นใหญ่ เหมาะกับคนชอบของน่ารัก แต่งห้อง หรือกอดนอน",
    color: "#f6e8c8",
    imageUrl: "assets/product-images/goose-plush-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJGaffoT",
  },
  {
    id: "custom-music-plaque-nfc",
    title: "กรอบเพลงพร้อมรูปและ NFC",
    icon: "🎵",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 45],
    occasions: ["anniversary", "birthday", "celebrate", "justbecause"],
    personality: ["creative", "homebody", "tech"],
    budget: ["medium"],
    price: "ประมาณ 600–1,200 บาท",
    currentPrice: "฿731",
    text: "ของขวัญสั่งทำที่ใส่รูป เพลง และข้อความส่วนตัว เหมาะกับวันครบรอบ งานแต่ง หรือคนพิเศษ",
    color: "#d8c0ff",
    imageUrl: "assets/product-images/custom-music-plaque-nfc.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4VadJYhsjT",
  },
  {
    id: "crochet-sunflower-bouquet",
    title: "ช่อดอกไม้ถักไหมพรม",
    icon: "🌻",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–800 บาท",
    currentPrice: "฿357",
    text: "ช่อดอกไม้แฮนด์เมดที่เก็บได้นาน เหมาะกับวันเกิด วันครบรอบ หรือให้กำลังใจคนสำคัญ",
    color: "#ffce4d",
    imageUrl: "assets/product-images/crochet-sunflower-bouquet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4qDTiV1TYg",
  },
  {
    id: "mens-wallet-belt-gift-set",
    title: "เซ็ตกระเป๋าสตางค์และเข็มขัดผู้ชาย",
    icon: "👔",
    recipients: ["partner", "family", "friend", "coworker"],
    genders: ["male"],
    ageRange: [22, 65],
    occasions: ["birthday", "anniversary", "celebrate", "thankyou", "festival"],
    personality: ["practical"],
    budget: ["medium"],
    price: "ประมาณ 900–1,500 บาท",
    currentPrice: "฿1,028",
    text: "เซ็ตของใช้ผู้ชายที่ดูสุภาพและใช้งานได้จริง เหมาะกับแฟน คุณพ่อ ผู้ใหญ่ หรือโอกาสที่อยากให้ดูพรีเมียมขึ้น",
    color: "#303846",
    imageUrl: "assets/product-images/mens-wallet-belt-gift-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5VTAgAsqQs",
  },
  {
    id: "playboy-womens-watch-set",
    title: "เซ็ตนาฬิกาผู้หญิง PLAYBOY",
    icon: "⌚",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [18, 55],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["practical", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,430",
    text: "เซ็ตนาฬิกาพร้อมกล่องของขวัญ เหมาะกับแฟน เพื่อนสนิท หรือคนที่ชอบของใช้สวย ๆ ที่ใส่ได้จริง",
    color: "#e6c7c0",
    imageUrl: "assets/product-images/playboy-womens-watch-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7AbOfRdoMC",
  },
  {
    id: "duck-night-light",
    title: "โคมไฟกลางคืนรูปเป็ด",
    icon: "💡",
    recipients: ["kid", "friend", "partner", "self"],
    genders: ["unisex"],
    ageRange: [3, 35],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿154",
    text: "โคมไฟซิลิโคนแสงนุ่มสำหรับหัวเตียง เหมาะกับเด็ก คนชอบแต่งห้อง หรือของขวัญน่ารักงบไม่แรง",
    color: "#ffe88a",
    imageUrl: "assets/product-images/duck-night-light.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/110lKAiU8P",
  },
  {
    id: "aurora-gold-bracelet",
    title: "กำไลทองคำ AURORA",
    icon: "💛",
    recipients: ["partner", "family", "self"],
    genders: ["female"],
    ageRange: [22, 75],
    occasions: ["anniversary", "birthday", "celebrate", "thankyou"],
    personality: ["practical", "creative"],
    budget: ["premium"],
    price: "ประมาณ 3,000 บาทขึ้นไป",
    currentPrice: "฿3,990",
    text: "ของขวัญมูลค่าสูงที่เก็บได้นาน เหมาะกับแฟน ผู้ใหญ่ หรือโอกาสสำคัญที่ต้องการความพรีเมียม",
    color: "#f5d36b",
    imageUrl: "assets/product-images/aurora-gold-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/70HyTQeSgb",
  },
  {
    id: "birthday-candle-jewelry-box",
    title: "กล่องของขวัญเทียนเค้กและเครื่องประดับ",
    icon: "🎂",
    recipients: ["partner", "friend", "self"],
    genders: ["female"],
    ageRange: [14, 40],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 200–500 บาท",
    currentPrice: "฿240",
    text: "กล่องของขวัญหน้าตาน่ารักพร้อมกลิ่นอายวันเกิด เหมาะกับแฟน เพื่อนสนิท หรือคนที่ชอบของกุ๊กกิ๊ก",
    color: "#ffd0df",
    imageUrl: "assets/product-images/birthday-candle-jewelry-box.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/AAF0FK591O",
  },
  {
    id: "moomin-plush-pillow",
    title: "ตุ๊กตามูมินกอดนุ่ม",
    icon: "🤍",
    recipients: ["partner", "friend", "kid", "self"],
    genders: ["female", "unisex"],
    ageRange: [6, 40],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–900 บาท",
    currentPrice: "฿490 - ฿790",
    text: "ตุ๊กตาคาแรกเตอร์นุ่ม ๆ สำหรับกอดหรือแต่งห้อง เหมาะกับคนชอบของน่ารักและของขวัญอบอุ่น",
    color: "#d8ecff",
    imageUrl: "assets/product-images/moomin-plush-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6L2HgRNoHY",
  },
  {
    id: "liverpool-man-u-mug",
    title: "แก้วฟุตบอล Liverpool 7-0 Man U",
    icon: "⚽",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 60],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "active", "creative"],
    budget: ["small"],
    price: "ประมาณ 100–250 บาท",
    currentPrice: "฿162",
    text: "แก้วลายฟุตบอลสำหรับแฟนบอล เหมาะกับเพื่อนสนิท เพื่อนร่วมงาน หรือคนที่อินโมเมนต์ทีมโปรด",
    color: "#dce8f4",
    imageUrl: "assets/product-images/liverpool-man-u-mug.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8pjcf8yCHp",
  },
  {
    id: "shy-boy-table-lamp",
    title: "โคมไฟตั้งโต๊ะ Shy Boy",
    icon: "🛋️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["unisex"],
    ageRange: [12, 55],
    occasions: ["birthday", "festival", "justbecause", "thankyou"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–700 บาท",
    currentPrice: "฿283",
    text: "โคมไฟตั้งโต๊ะดีไซน์น่ารักสำหรับแต่งห้องหรือโต๊ะทำงาน เหมาะกับคนอยู่บ้านและสายของแต่งห้อง",
    color: "#f0dfc8",
    imageUrl: "assets/product-images/shy-boy-table-lamp.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EAC1Mi8",
  },
  {
    id: "menspe-crossbody-bag",
    title: "กระเป๋าสะพายข้างผู้ชาย MENSPE",
    icon: "🎒",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["practical", "active", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–600 บาท",
    currentPrice: "฿290",
    text: "กระเป๋าสะพายข้างทรงเรียบ ใช้ได้ทุกวัน เหมาะกับผู้ชายที่ชอบของ practical และพกของจำเป็นน้อยชิ้น",
    color: "#1f2329",
    imageUrl: "assets/product-images/menspe-crossbody-bag.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9AMT58t3VA",
  },
  {
    id: "civago-lucky-puppy-tumbler",
    title: "แก้วน้ำ CIVAGO x Lucky Puppy",
    icon: "🥤",
    recipients: ["friend", "partner", "coworker", "kid", "self"],
    genders: ["female", "unisex"],
    ageRange: [10, 45],
    occasions: ["birthday", "festival", "justbecause", "thankyou"],
    personality: ["practical", "homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–600 บาท",
    currentPrice: "฿399",
    text: "แก้วน้ำลายคาแรกเตอร์น่ารัก ใช้งานได้ทุกวัน เหมาะกับคนทำงาน นักเรียน หรือคนชอบของพกพาสวย ๆ",
    color: "#d6c0aa",
    imageUrl: "assets/product-images/civago-lucky-puppy-tumbler.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EAOljX6",
  },
  {
    id: "eloop-magsafe-powerbank",
    title: "พาวเวอร์แบงก์ Eloop MagCharge",
    icon: "🔋",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [14, 65],
    occasions: ["birthday", "festival", "celebrate", "thankyou", "justbecause"],
    personality: ["tech", "active", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–1,000 บาท",
    currentPrice: "฿428",
    text: "พาวเวอร์แบงก์ชาร์จเร็วสำหรับคนใช้มือถือหนัก เดินทางบ่อย หรือชอบแกดเจ็ตที่ใช้งานได้จริง",
    color: "#5d636b",
    imageUrl: "assets/product-images/eloop-magsafe-powerbank.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6pyYJ2kRRw",
  },
  {
    id: "samurai-umbrella",
    title: "ร่มด้ามดาบซามูไร",
    icon: "☂️",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "active", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–700 บาท",
    currentPrice: "฿456",
    text: "ร่มดีไซน์ดาบซามูไรสำหรับคนชอบอนิเมะหรือของไม่เหมือนใคร เป็นของใช้จริงที่มีคาแรกเตอร์ชัด",
    color: "#2d3038",
    imageUrl: "assets/product-images/samurai-umbrella.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/gNuxp8wKp",
  },
  {
    id: "instax-mini-evo-camera",
    title: "กล้อง Fujifilm Instax Mini Evo",
    icon: "📸",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "celebrate"],
    personality: ["creative", "tech", "active"],
    budget: ["premium"],
    price: "ประมาณ 5,000 บาทขึ้นไป",
    currentPrice: "฿6,536",
    text: "กล้อง instant hybrid สำหรับคนชอบถ่ายรูปและเก็บโมเมนต์ เหมาะกับของขวัญชิ้นใหญ่ในโอกาสสำคัญ",
    color: "#d6c2a8",
    imageUrl: "assets/product-images/instax-mini-evo-camera.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJUFswcd",
  },
  {
    id: "aroma-humidifier",
    title: "เครื่องพ่นน้ำหอมอโรม่า",
    icon: "🌫️",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "thankyou", "festival", "justbecause"],
    personality: ["homebody", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–700 บาท",
    currentPrice: "฿377",
    text: "เครื่องพ่นอโรม่าสำหรับห้องนอนหรือโต๊ะทำงาน เหมาะกับคนอยู่บ้าน รักความสบาย หรืออยากให้พื้นที่ผ่อนคลายขึ้น",
    color: "#dfe8dc",
    imageUrl: "assets/product-images/aroma-humidifier.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/gNuyYCgyI",
  },
  {
    id: "portable-mini-projector",
    title: "โปรเจกเตอร์พกพา",
    icon: "📽️",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["tech", "homebody", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,357",
    text: "โปรเจกเตอร์ขนาดเล็กสำหรับดูหนัง เล่นเกม หรือจัดมุมพักผ่อนในห้อง เหมาะกับสายเทคและคนชอบอยู่บ้าน",
    color: "#d9ecff",
    imageUrl: "assets/product-images/portable-mini-projector.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8V6mJACokr",
  },
  {
    id: "kai-hair-clipper",
    title: "ปัตตาเลี่ยนไฟฟ้า KAI",
    icon: "✂️",
    recipients: ["partner", "family", "friend", "self"],
    genders: ["male"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "thankyou", "justbecause"],
    personality: ["practical", "tech"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,689",
    text: "เครื่องตัดผมไฟฟ้าสำหรับคนที่ชอบดูแลตัวเองหรืออยากมีอุปกรณ์ใช้เองที่บ้าน เหมาะกับของขวัญผู้ชายสาย practical",
    color: "#2d2d2d",
    imageUrl: "assets/product-images/kai-hair-clipper.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJVFkscL",
  },
  {
    id: "twilight-library-diy-book-nook",
    title: "ชุด DIY บ้านหนังสือจิ๋ว Twilight Library",
    icon: "📚",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["unisex"],
    ageRange: [12, 60],
    occasions: ["birthday", "festival", "justbecause", "celebrate"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–800 บาท",
    currentPrice: "฿438",
    text: "ชุดประกอบบ้านหนังสือจิ๋วพร้อมไฟ LED เหมาะกับคนรักหนังสือ งานคราฟต์ และของแต่งห้องที่มีเรื่องราว",
    color: "#8b5a3c",
    imageUrl: "assets/product-images/twilight-library-diy-book-nook.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9fIjhg8VHc",
  },
  {
    id: "enchen-shaver-gift-set",
    title: "เซ็ตเครื่องโกนหนวด Enchen",
    icon: "🪒",
    recipients: ["partner", "family", "friend", "self"],
    genders: ["male"],
    ageRange: [18, 70],
    occasions: ["birthday", "festival", "thankyou", "justbecause"],
    personality: ["practical", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–900 บาท",
    currentPrice: "฿461",
    text: "ชุดเครื่องโกนหนวดและอุปกรณ์ดูแลตัวเองสำหรับผู้ชาย เหมาะกับของขวัญที่ใช้งานได้จริงทุกวัน",
    color: "#17191d",
    imageUrl: "assets/product-images/enchen-shaver-gift-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/2LW8yILgyA",
  },
  {
    id: "thai-funny-tshirt",
    title: "เสื้อยืดลายไทยสายฮา",
    icon: "👕",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [13, 45],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–500 บาท",
    currentPrice: "฿323",
    text: "เสื้อยืดลายขำ ๆ สำหรับเพื่อนหรือคนที่ชอบมุกไทย ใส่เป็นของขวัญสนุก ๆ ได้ดี",
    color: "#f47b25",
    imageUrl: "assets/product-images/thai-funny-tshirt.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6ff88Spllx",
  },
  {
    id: "enter-key-stress-pillow",
    title: "หมอนปุ่ม Enter แก้เครียด",
    icon: "⌨️",
    recipients: ["friend", "coworker", "partner", "self"],
    genders: ["unisex"],
    ageRange: [12, 55],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody", "practical", "tech"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿159",
    text: "หมอนปุ่ม Enter ขนาดใหญ่สำหรับกดระบายอารมณ์ เหมาะกับเพื่อนร่วมงาน คนทำงานหน้าคอม หรือของขวัญสายฮา",
    color: "#111111",
    imageUrl: "assets/product-images/enter-key-stress-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6VLhwG7Mn3",
  },
  {
    id: "hello-kitty-ceramic-cup",
    title: "แก้วเซรามิก Hello Kitty",
    icon: "🎀",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [10, 45],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–700 บาท",
    currentPrice: "฿458",
    text: "แก้วเซรามิกคาแรกเตอร์พร้อมแพ็กเกจของขวัญ เหมาะกับคนชอบ Hello Kitty หรือของใช้ที่น่ารักเป็นพิเศษ",
    color: "#ef3f3f",
    imageUrl: "assets/product-images/hello-kitty-ceramic-cup.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4VadYzY1uk",
  },
  {
    id: "personalized-steel-bracelet",
    title: "กำไลข้อมือสแตนเลสสลักชื่อ",
    icon: "🔗",
    recipients: ["partner", "friend", "self"],
    genders: ["unisex"],
    ageRange: [14, 45],
    occasions: ["anniversary", "birthday", "festival", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿139",
    text: "กำไลข้อมือสลักชื่อหรือข้อความส่วนตัว เหมาะกับของขวัญคู่ วาเลนไทน์ วันเกิด หรือของแทนใจงบเบา",
    color: "#1f1f1f",
    imageUrl: "assets/product-images/personalized-steel-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/Ll52daPqv",
  },
  {
    id: "huawei-watch-fit-5",
    title: "HUAWEI WATCH FIT 5",
    icon: "⌚",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 65],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["tech", "active", "practical"],
    budget: ["premium"],
    price: "ประมาณ 3,000 บาทขึ้นไป",
    currentPrice: "฿3,710",
    text: "สมาร์ทวอทช์สำหรับดูแลสุขภาพ ออกกำลัง และใช้งานประจำวัน เหมาะกับสายเทคหรือคนที่อยากดูแลตัวเองจริงจัง",
    color: "#dbe0e6",
    imageUrl: "assets/product-images/huawei-watch-fit-5.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5VTBCHSmlI",
  },
  {
    id: "gq-running-shorts",
    title: "กางเกงวิ่ง GQ Everyday",
    icon: "🏃",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [14, 55],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["active", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿155",
    text: "กางเกงขาสั้นสำหรับวิ่งหรือออกกำลัง ใส่ได้ทุกวัน เหมาะกับคนรักสุขภาพหรือคนที่ชอบของใช้จริง",
    color: "#6b7c68",
    imageUrl: "assets/product-images/gq-running-shorts.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7pr5yhZACX",
  },
  {
    id: "iron-man-arc-reactor-lamp",
    title: "แท่นชาร์จ MagSafe Arc Reactor Iron Man",
    icon: "🦾",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["tech", "practical", "creative"],
    budget: ["medium"],
    price: "ประมาณ 900-1,200 บาท",
    currentPrice: "฿947",
    text: "แท่นชาร์จมือถือแบบ MagSafe/ไร้สายธีม Arc Reactor Iron Man เหมาะกับแฟน Marvel คนชอบแกดเจ็ต หรือคนที่อยากได้ของใช้บนโต๊ะทำงานที่มีคาแรกเตอร์",
    color: "#2f3b4a",
    imageUrl: "assets/product-images/iron-man-arc-reactor-lamp.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EeOHbKf",
  },
  {
    id: "scented-candle-gift-box",
    title: "Gift Box เทียนหอม 3 กลิ่น",
    icon: "🕯️",
    recipients: ["friend", "partner", "coworker", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 300-500 บาท",
    currentPrice: "฿333",
    text: "กล่องของขวัญเทียนหอม 3 กลิ่นพร้อมแพ็กเกจผูกโบว์ เหมาะกับวันเกิด ปีใหม่ ของขอบคุณ หรือคนที่ชอบบรรยากาศห้องหอม ๆ",
    color: "#b56a4d",
    imageUrl: "assets/product-images/scented-candle-gift-box.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4AxncWKxa6",
  },
  {
    id: "soft-kettlebell",
    title: "เคตเทิลเบลล์แบบนุ่ม",
    icon: "🏋️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["active", "practical"],
    budget: ["small"],
    price: "ประมาณ 150-400 บาท",
    currentPrice: "฿170",
    text: "เคตเทิลเบลล์แบบนุ่มสำหรับออกกำลังกายที่บ้าน เหมาะกับคนรักสุขภาพ มือใหม่ฟิตเนส หรือคนที่อยากเริ่มขยับตัวแบบจริงจัง",
    color: "#4a4a4a",
    imageUrl: "assets/product-images/soft-kettlebell.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1LdcFZLZT3",
  },
  {
    id: "3ce-blur-matte-lipstick",
    title: "3CE Blur Matte Lipstick",
    icon: "💄",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [15, 45],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400-800 บาท",
    currentPrice: "฿455",
    text: "ลิปสติกเนื้อแมตต์โทนใช้ง่าย เหมาะกับคนชอบแต่งหน้า บิวตี้ หรือของขวัญชิ้นเล็กที่ดูเลือกมาแล้ว",
    color: "#e94b75",
    imageUrl: "assets/product-images/3ce-blur-matte-lipstick.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7VEqPoAQ4c",
  },
  {
    id: "dior-addict-lip-glow",
    title: "Dior Addict Lip Glow",
    icon: "💋",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [15, 50],
    occasions: ["birthday", "anniversary", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["medium"],
    price: "ประมาณ 800-1,200 บาท",
    currentPrice: "฿828",
    text: "ลิปโกลว์โทนชมพูหวานสำหรับคนชอบบิวตี้ ใช้ง่าย ดูเป็นของขวัญที่พรีเมียมขึ้น เหมาะกับวันเกิดหรือของเซอร์ไพรส์คนพิเศษ",
    color: "#f4a3b8",
    imageUrl: "assets/product-images/dior-addict-lip-glow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1BKmsXe5WX",
  },
  {
    id: "mac-sleek-satin-lipstick",
    title: "MAC Maximal Sleek Satin Lipstick",
    icon: "💄",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["medium"],
    price: "ประมาณ 800-1,000 บาท",
    currentPrice: "฿820",
    text: "ลิปสติก MAC เนื้อซาติน โทนสีชัดและดูพรีเมียม เหมาะกับคนชอบแต่งหน้า หรือของขวัญบิวตี้ที่ดูคลาสสิกไม่พลาดง่าย",
    color: "#b7384f",
    imageUrl: "assets/product-images/mac-sleek-satin-lipstick.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5Aqvdyz8FE",
  },
  {
    id: "squishy-dessert-stress-toy",
    title: "บีบเล่นคลายเครียดรูปเค้กซูเฟล่",
    icon: "🍰",
    recipients: ["friend", "partner", "kid", "self"],
    genders: ["female", "unisex"],
    ageRange: [8, 35],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small"],
    price: "ประมาณ 150-300 บาท",
    currentPrice: "฿165",
    text: "ของเล่นบีบคลายเครียดรูปเค้กซูเฟล่น่ารัก เหมาะกับคนชอบของจุกจิก สายขนม หรือคนที่อยากได้ของวางโต๊ะให้หยิบเล่นเพลิน ๆ",
    color: "#f6c9d4",
    imageUrl: "assets/product-images/squishy-dessert-stress-toy.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7fYGdAMv4X",
  },
  {
    id: "sumor-polarized-sunglasses",
    title: "SUMOR แว่นกันแดด Polarized",
    icon: "🕶️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["practical", "active", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 400-700 บาท",
    currentPrice: "฿423",
    text: "แว่นกันแดดทรงวินเทจเลนส์ polarized ใส่ได้ทั้งผู้ชายและผู้หญิง เหมาะกับคนชอบแฟชั่น ท่องเที่ยว หรือของใช้จริงที่ดูเท่",
    color: "#c9b39d",
    imageUrl: "assets/product-images/sumor-polarized-sunglasses.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/70IZqFJE59",
  },
  {
    id: "crocs-lego-limited-clog",
    title: "CROCS x LEGO Limited Edition",
    icon: "🧱",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical", "active"],
    budget: ["large"],
    price: "ประมาณ 1,500-2,500 บาท",
    currentPrice: "฿1,990",
    text: "รองเท้า Crocs รุ่นพิเศษคอลแลบ LEGO สีสดและมีคาแรกเตอร์ เหมาะกับคนชอบแฟชั่นสนุก ๆ ของ limited หรือสายสะสมที่ไม่อยากได้ของธรรมดา",
    color: "#f2c94c",
    imageUrl: "assets/product-images/crocs-lego-limited-clog.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6AjSqmtyqq",
  },
  {
    id: "yamaha-f310-acoustic-guitar",
    title: "Yamaha F310 Acoustic Guitar",
    icon: "🎸",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 60],
    occasions: ["birthday", "anniversary", "celebrate", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["premium"],
    price: "ประมาณ 5,000-7,000 บาท",
    currentPrice: "฿5,699",
    text: "กีตาร์โปร่ง Yamaha F310 สำหรับคนรักดนตรีหรือคนที่อยากเริ่มเล่นจริงจัง เป็นของขวัญชิ้นใหญ่ที่มีความหมายและใช้ได้นาน",
    color: "#9b6a3c",
    imageUrl: "assets/product-images/yamaha-f310-acoustic-guitar.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9KgUd9xc8X",
  },
  {
    id: "swarovski-mens-leather-bracelet",
    title: "สร้อยข้อมือหนังถัก Swarovski Style",
    icon: "🔗",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["medium"],
    price: "ประมาณ 700-900 บาท",
    currentPrice: "฿725",
    text: "สร้อยข้อมือหนังถักโทนดำสไตล์เรียบเท่ เหมาะกับผู้ชายที่ชอบเครื่องประดับ ใส่ได้ทุกวัน หรือเป็นของขวัญคู่แบบไม่หวานเกินไป",
    color: "#1d1b1b",
    imageUrl: "assets/product-images/swarovski-mens-leather-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6pz9ekCrXf",
  },
  {
    id: "bitcoin-standard-book",
    title: "หนังสือ The Bitcoin Standard",
    icon: "₿",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["tech", "practical"],
    budget: ["small"],
    price: "ประมาณ 300-500 บาท",
    currentPrice: "฿352",
    text: "หนังสือ The Bitcoin Standard สำหรับคนสนใจ Bitcoin การเงินทางเลือก เศรษฐศาสตร์ หรือการลงทุน เป็นของขวัญสายความรู้ที่เลือกมาแล้วดูตั้งใจ",
    color: "#a66a2f",
    imageUrl: "assets/product-images/bitcoin-standard-book.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/3B5rIoaWnl",
  },
  {
    id: "success-outside-box-book",
    title: "หนังสือ สำเร็จนอกกรอบ",
    icon: "📘",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "celebrate", "thankyou", "justbecause"],
    personality: ["practical", "creative"],
    budget: ["small"],
    price: "ประมาณ 200-300 บาท",
    currentPrice: "฿207",
    text: "หนังสือแนวพัฒนาตัวเองและธุรกิจสำหรับคนที่อยากคิดนอกกรอบ ทำงานให้เก่งขึ้น หรือมองความสำเร็จในมุมใหม่ เป็นของขวัญสายความรู้ที่อ่านแล้วได้ไอเดียต่อยอด",
    color: "#2fb8c7",
    imageUrl: "assets/product-images/success-outside-box-book.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8AUXG4k3al",
  },
  {
    id: "broken-money-book",
    title: "หนังสือ เงินปล้นโลก Broken Money",
    icon: "📘",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "celebrate", "thankyou", "justbecause"],
    personality: ["tech", "practical"],
    budget: ["medium"],
    price: "ประมาณ 400-600 บาท",
    currentPrice: "฿468",
    text: "หนังสือ Broken Money ฉบับไทย สำหรับคนสนใจระบบการเงิน เศรษฐกิจ เทคโนโลยี และมุมมองเรื่องเงินในโลกยุคใหม่ เหมาะเป็นของขวัญสายอ่านจริงจังที่อยากเข้าใจโลกการเงินลึกขึ้น",
    color: "#1f7c8d",
    imageUrl: "assets/product-images/broken-money-book.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/50XVUKH2qq",
  },
  {
    id: "tomica-lamborghini-countach",
    title: "Tomica Lamborghini Countach LPI 800-4",
    icon: "🏎️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [8, 55],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 200-300 บาท",
    currentPrice: "฿215",
    text: "รถโมเดล Tomica Lamborghini Countach ขนาด 1/64 จาก Takara Tomy เหมาะกับคนชอบรถ ของสะสม ของเล่นคุณภาพ หรืออยากได้ของขวัญชิ้นเล็กที่ดูมีคาแรกเตอร์",
    color: "#e23b3b",
    imageUrl: "assets/product-images/tomica-lamborghini-countach.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/30mR6p28Rx",
  },
  {
    id: "kawasaki-ninja-h2r-model",
    title: "โมเดล Kawasaki Ninja H2R",
    icon: "🏍️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [10, 55],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 100-300 บาท",
    currentPrice: "฿170",
    text: "โมเดลรถมอเตอร์ไซค์ Kawasaki Ninja H2R สไตล์สปอร์ตสำหรับคนชอบรถ ของสะสม หรือของแต่งโต๊ะ เป็นของขวัญชิ้นเล็กที่ดูเท่และมีคาแรกเตอร์ชัด",
    color: "#1f1f1f",
    imageUrl: "assets/product-images/kawasaki-ninja-h2r-model.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1gH3WTIoNm",
  },
  {
    id: "popmart-naruto-akatsuki-set",
    title: "POP MART Naruto Akatsuki Figure Set",
    icon: "🍥",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "anniversary", "festival", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["premium"],
    price: "ประมาณ 4,000-5,000 บาท",
    currentPrice: "฿4,299",
    text: "เซ็ตฟิกเกอร์ POP MART Naruto Shippuden ธีม Akatsuki แบบ whole set สำหรับแฟน Naruto และสายสะสม เป็นของขวัญชิ้นใหญ่ที่ดูตั้งใจและมีคุณค่าทางใจมาก",
    color: "#d0192f",
    imageUrl: "assets/product-images/popmart-naruto-akatsuki-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/2g9aiSxd2D",
  },
  {
    id: "popmart-demon-slayer-battle-set",
    title: "POP MART Demon Slayer Battle Series Figure Set",
    icon: "⚔️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "anniversary", "festival", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["premium"],
    price: "ประมาณ 5,000-6,000 บาท",
    currentPrice: "฿5,160",
    text: "เซ็ตฟิกเกอร์ POP MART Demon Slayer: Kimetsu no Yaiba Battle Series แบบ whole set สำหรับแฟนดาบพิฆาตอสูรและสายสะสม เป็นของขวัญพรีเมียมที่เหมาะกับคนอินอนิเมะจริงจัง",
    color: "#7b1414",
    imageUrl: "assets/product-images/popmart-demon-slayer-battle-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9pclT0eNOl",
  },
  {
    id: "ganesha-purple-bracelet",
    title: "กำไลพระพิฆเนศ พลอยสีม่วง",
    icon: "🕉️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000-1,500 บาท",
    currentPrice: "฿1,475",
    text: "กำไลพระพิฆเนศพลอยสีม่วงสำหรับคนที่ชอบเครื่องประดับสายมู มีความหมายเรื่องปัญญา การเริ่มต้นใหม่ และกำลังใจ เหมาะกับของขวัญให้ผู้ใหญ่ คนทำงาน หรือคนที่กำลังเริ่มสิ่งใหม่ในชีวิต",
    color: "#8b4bb3",
    imageUrl: "assets/product-images/ganesha-purple-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8fQo9tKFq5",
  },
  {
    id: "guan-yin-white-bracelet",
    title: "กำไลเจ้าแม่กวนอิม พลอยสีขาว",
    icon: "🤍",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["medium"],
    price: "ประมาณ 1,000-1,500 บาท",
    currentPrice: "฿1,277",
    text: "กำไลเจ้าแม่กวนอิมพลอยสีขาวสำหรับคนที่ชอบเครื่องประดับสายมู โทนสุภาพและมีความหมายเรื่องความเมตตา การคุ้มครอง ความสงบใจ และการเริ่มต้นใหม่ เหมาะเป็นของขวัญให้ผู้ใหญ่ คนทำงาน หรือคนที่อยากส่งกำลังใจแบบละมุน",
    color: "#c7a68f",
    imageUrl: "assets/product-images/guan-yin-white-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8AUXZfRXks",
  },
  {
    id: "uniqlo-ut-naruto-shueisha-tshirt",
    title: "เสื้อยืด Uniqlo UT Naruto Shueisha 100th",
    icon: "🍥",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["medium"],
    price: "ประมาณ 500-700 บาท",
    currentPrice: "฿559",
    text: "เสื้อยืด Uniqlo UT ลาย Naruto x Shueisha 100th สีดำ ใส่ง่ายและมีความเป็นแฟนด้อมแบบไม่เยอะเกินไป เหมาะกับคนชอบนารูโตะ อนิเมะ เสื้อยืดคาแรกเตอร์ หรือของขวัญที่ใช้ได้จริงในชีวิตประจำวัน",
    color: "#1f1f1f",
    imageUrl: "assets/product-images/uniqlo-ut-naruto-shueisha-tshirt.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6VMK24mtAu",
  },
  {
    id: "manchester-united-25-26-jersey",
    title: "เสื้อฟุตบอล Manchester United 25/26",
    icon: "⚽",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 55],
    occasions: ["birthday", "celebrate", "festival", "justbecause"],
    personality: ["sporty", "practical"],
    budget: ["premium"],
    price: "ประมาณ 1,000-1,500 บาท",
    currentPrice: "฿1,412",
    text: "เสื้อฟุตบอล Manchester United ฤดูกาล 25/26 สีแดง เหมาะกับแฟนบอลแมนยู คนชอบฟุตบอล หรือคนที่ชอบเสื้อกีฬาใส่ได้จริง เป็นของขวัญที่ตรงใจมากถ้ารู้ว่าเขาเชียร์ทีมนี้",
    color: "#d71920",
    imageUrl: "assets/product-images/manchester-united-25-26-jersey.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7fYHQl97wm",
  },
  {
    id: "playstation-5-slim-console",
    title: "PlayStation 5 Slim Console",
    icon: "🎮",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "celebrate", "festival", "justbecause"],
    personality: ["gamer", "creative", "tech"],
    budget: ["luxury"],
    price: "ประมาณ 20,000-25,000 บาท",
    currentPrice: "฿22,950",
    text: "เครื่องเกม PlayStation 5 Slim สำหรับคนชอบเกม เทคโนโลยี และความบันเทิงในบ้าน เป็นของขวัญชิ้นใหญ่ที่เหมาะกับแฟนเกมตัวจริง หรือโอกาสพิเศษที่อยากให้แบบว้าวสุด ๆ",
    color: "#f5f7ff",
    imageUrl: "assets/product-images/playstation-5-slim-console.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6VMK2sFHns",
  },
  {
    id: "nintendo-switch-2-console",
    title: "Nintendo Switch 2 Console",
    icon: "🎮",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [10, 45],
    occasions: ["birthday", "celebrate", "festival", "justbecause"],
    personality: ["gamer", "creative", "tech"],
    budget: ["luxury"],
    price: "ประมาณ 15,000-18,000 บาท",
    currentPrice: "฿15,800",
    text: "เครื่องเกม Nintendo Switch 2 สำหรับคนชอบเกมและความบันเทิงแบบพกพา เหมาะกับแฟน Nintendo คนเล่นเกมกับเพื่อนหรือครอบครัว และคนที่อยากได้ของขวัญชิ้นใหญ่ที่ใช้ได้ทั้งที่บ้านและนอกบ้าน",
    color: "#e60012",
    imageUrl: "assets/product-images/nintendo-switch-2-console.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6ffkFZ4kbY",
  },
  {
    id: "oppo-enco-buds3-earbuds",
    title: "OPPO Enco Buds3 หูฟังไร้สาย",
    icon: "🎧",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [13, 55],
    occasions: ["birthday", "newjob", "celebrate", "justbecause", "festival"],
    personality: ["practical", "tech", "music"],
    budget: ["medium"],
    price: "ประมาณ 400-600 บาท",
    currentPrice: "฿491",
    text: "หูฟังไร้สาย OPPO Enco Buds3 สำหรับฟังเพลง ประชุมออนไลน์ ดูหนัง หรือใช้เดินทางทุกวัน เป็นของขวัญที่ใช้งานได้จริง เหมาะกับคนชอบเพลง เทคโนโลยี และของชิ้นเล็กที่หยิบใช้บ่อย",
    color: "#e9f0ff",
    imageUrl: "assets/product-images/oppo-enco-buds3-earbuds.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6pzASKP2zx",
  },
  {
    id: "sony-wh-xb910n-headphones",
    title: "Sony WH-XB910N หูฟังครอบหูไร้สาย",
    icon: "🎧",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [15, 55],
    occasions: ["birthday", "newjob", "celebrate", "justbecause", "festival"],
    personality: ["music", "tech", "practical"],
    budget: ["medium"],
    price: "ประมาณ 500-700 บาท",
    currentPrice: "฿571",
    text: "หูฟังครอบหู Sony WH-XB910N สำหรับคนชอบฟังเพลง ดูหนัง เล่นเกม หรือใช้ทำงานแบบมีสมาธิ มีภาพลักษณ์จริงจังขึ้นกว่า earbud เล็ก ๆ เหมาะกับคนรักเสียงเพลงและของใช้เทคโนโลยีที่หยิบใช้ได้ทุกวัน",
    color: "#243f8f",
    imageUrl: "assets/product-images/sony-wh-xb910n-headphones.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5VTnXyqmxw",
  },
  {
    id: "olyps-thai-gaming-keyboard",
    title: "OLYPS คีย์บอร์ดภาษาไทยเกมมิ่ง",
    icon: "⌨️",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [10, 55],
    occasions: ["birthday", "newjob", "celebrate", "justbecause", "festival"],
    personality: ["gamer", "tech", "practical"],
    budget: ["budget"],
    price: "ประมาณ 200-300 บาท",
    currentPrice: "฿258",
    text: "คีย์บอร์ด OLYPS แบบไทยสำหรับใช้กับคอม ทำงาน เรียน เล่นเกม หรือแต่งโต๊ะทำงาน เสียงรบกวนต่ำและมีสีสันน่ารัก เป็นของขวัญใช้งานจริงที่เหมาะกับคนใช้คอมบ่อยและสายจัดโต๊ะ",
    color: "#2e86de",
    imageUrl: "assets/product-images/olyps-thai-gaming-keyboard.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7fYICGSWxc",
  },
  {
    id: "jujutsu-kaisen-season-2-keyboard",
    title: "Keyboard EGA x Jujutsu Kaisen Season 2",
    icon: "⌨️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "celebrate", "festival", "justbecause"],
    personality: ["gamer", "creative", "tech"],
    budget: ["premium"],
    price: "ประมาณ 2,000-2,500 บาท",
    currentPrice: "฿2,205",
    text: "คีย์บอร์ด EGA ลาย Jujutsu Kaisen Season 2 สำหรับแฟนอนิเมะ สายเกมมิ่ง และคนชอบแต่งโต๊ะคอม เป็นของขวัญที่ดูพิเศษกว่าคีย์บอร์ดทั่วไป เพราะมีทั้งฟังก์ชันใช้งานจริงและความเป็นของสะสมแฟนด้อม",
    color: "#8ed6ff",
    imageUrl: "assets/product-images/jujutsu-kaisen-season-2-keyboard.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1Vxer11Se0",
  },
  {
    id: "custom-name-silver-necklace",
    title: "สร้อยคอเงินแท้สลักชื่อ",
    icon: "💎",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [15, 55],
    occasions: ["birthday", "anniversary", "valentine", "celebrate", "justbecause"],
    personality: ["romantic", "creative", "practical"],
    budget: ["medium"],
    price: "ประมาณ 700-1,000 บาท",
    currentPrice: "฿784",
    text: "สร้อยคอเงินแท้สลักชื่อตามสั่ง เหมาะกับคนที่ชอบของขวัญเฉพาะตัวและมีความหมาย เช่น คนรัก เพื่อนสนิท หรือคนในครอบครัว ราคาอาจเปลี่ยนตามจำนวนตัวอักษรและจี้ที่เลือก",
    color: "#d9d3ff",
    imageUrl: "assets/product-images/custom-name-silver-necklace.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/2qT2SRBTFI",
  },
  {
    id: "roblox-thai-gift-card-300",
    title: "Roblox Gift Card Thailand 300 บาท",
    icon: "🎮",
    recipients: ["friend", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [8, 25],
    occasions: ["birthday", "celebrate", "festival", "justbecause"],
    personality: ["gamer", "creative"],
    budget: ["medium"],
    price: "ประมาณ 300-400 บาท",
    currentPrice: "฿350",
    text: "บัตรเติม Roblox 300 บาทสำหรับผู้เล่น Roblox ในไทย เหมาะกับเด็ก วัยรุ่น หรือคนที่เล่น Roblox เป็นประจำ เป็นของขวัญดิจิทัลที่เลือกง่าย ใช้ได้จริง และถูกใจมากถ้ารู้ว่าเขาเล่นเกมนี้",
    color: "#111111",
    imageUrl: "assets/product-images/roblox-thai-gift-card-300.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/2qT2T1wf7Q",
  },
  {
    id: "one-piece-mini-building-blocks",
    title: "JoyToy บล็อกตัวต่อ One Piece",
    icon: "🏴‍☠️",
    recipients: ["friend", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [8, 35],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["budget"],
    price: "ประมาณ 50 บาท",
    currentPrice: "฿48",
    text: "บล็อกตัวต่อคาแรกเตอร์ One Piece ชิ้นเล็กน่ารัก เหมาะกับแฟนวันพีช คนชอบอนิเมะ ของสะสม หรือของขวัญงบเบา ๆ ที่ยังมีความเฉพาะตัวและเลือกตัวละครได้ตามคนรับ",
    color: "#29b6f6",
    imageUrl: "assets/product-images/one-piece-mini-building-blocks.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/3LPJ4WzbRD",
  },
  {
    id: "lego-classic-10696-creative-brick-box",
    title: "LEGO Classic 10696 Creative Brick Box",
    icon: "🧱",
    recipients: ["friend", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [4, 45],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["premium"],
    price: "ประมาณ 1,000-1,500 บาท",
    currentPrice: "฿1,360",
    text: "LEGO Classic กล่องตัวต่อสร้างสรรค์ 484 ชิ้น เหมาะกับเด็ก คนชอบต่อเลโก้ ครอบครัว หรือผู้ใหญ่ที่ชอบงานอดิเรกเชิงสร้างสรรค์ เป็นของขวัญที่เล่นได้นานและเปิดพื้นที่ให้ต่อได้หลายแบบ",
    color: "#f9c900",
    imageUrl: "assets/product-images/lego-classic-10696-creative-brick-box.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6pzBF2iTIR",
  },
  {
    id: "lego-speed-champions-ferrari-sf24",
    title: "LEGO Speed Champions Ferrari SF-24 F1",
    icon: "🏎️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [10, 55],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["creative", "sporty", "homebody"],
    budget: ["medium"],
    price: "ประมาณ 900-1,000 บาท",
    currentPrice: "฿904",
    text: "LEGO Speed Champions Ferrari SF-24 รถแข่ง F1 สำหรับคนชอบเลโก้ รถซิ่ง Formula 1 หรือของสะสมธีมยานยนต์ เป็นของขวัญที่ทั้งต่อสนุกและตั้งโชว์ได้ เหมาะกับแฟน Ferrari และสายรถแข่ง",
    color: "#d71920",
    imageUrl: "assets/product-images/lego-speed-champions-ferrari-sf24.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1BKoVobWj8",
  },
];
