function shopeeSearch(keyword) {
  return `https://shopee.co.th/search?keyword=${encodeURIComponent(keyword)}`;
}

const productCatalog = [
  {
    id: "tea-gift-set",
    title: "เซ็ตชา 3 รส",
    icon: "🍵",
    recipients: ["friend", "family", "coworker"],
    genders: ["unisex"],
    ageRange: [18, 75],
    occasions: ["birthday", "thankyou", "festival"],
    personality: ["foodie", "homebody", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–700 บาท",
    currentPrice: "฿269 - ฿449",
    text: "ของขวัญสุภาพ ให้ได้ทั้งเพื่อนร่วมงาน ผู้ใหญ่ และคนที่ชอบจิบอะไรอุ่น ๆ",
    color: "#bcebd7",
    imageUrl: "https://down-th.img.susercontent.com/file/th-11134207-81ztj-mnzsjh53whl2ce.webp",
    researchUrl:
      "https://shopee.co.th/%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D-%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%8A%E0%B8%B2-3-%E0%B8%8A%E0%B8%99%E0%B8%B4%E0%B8%94-%E0%B8%88%E0%B8%B2%E0%B8%81%E0%B9%81%E0%B8%9A%E0%B8%A3%E0%B8%99%E0%B8%94%E0%B9%8C-guru-tea-%E0%B8%8A%E0%B8%B2%E0%B8%A1%E0%B8%B0%E0%B8%A5%E0%B8%B4-%E0%B8%8A%E0%B8%B2%E0%B8%A2%E0%B8%AD%E0%B8%94%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%84%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9C%E0%B8%B6%E0%B9%89%E0%B8%87-%E0%B8%8A%E0%B8%B2%E0%B8%AB%E0%B8%AD%E0%B8%A1%E0%B8%AB%E0%B8%A1%E0%B8%B7%E0%B9%88%E0%B8%99%E0%B8%A5%E0%B8%B5%E0%B9%89-%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%82%E0%B8%B2%E0%B8%A2%E0%B8%94%E0%B8%B5-i.25099264.54508225154",
    affiliateUrl: "https://s.shopee.co.th/AKYQAVjVBI",
  },
  {
    id: "premium-snack-box",
    title: "กล่องขนมหรือถั่วพรีเมียม",
    icon: "🥜",
    recipients: ["friend", "family", "coworker"],
    genders: ["unisex"],
    ageRange: [18, 75],
    occasions: ["festival", "thankyou", "birthday"],
    personality: ["foodie", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–900 บาท",
    currentPrice: "฿389",
    text: "หยิบกินง่าย แพ็กสวย เหมาะกับเทศกาลและการฝากผู้ใหญ่แบบไม่เสี่ยงเกินไป",
    color: "#ffd8a8",
    imageUrl: "https://down-th.img.susercontent.com/file/dce6a2ab81ebddc0c1926db5fd6e6f80_tn",
    researchUrl:
      "https://shopee.co.th/Gift-Set-%E0%B8%81%E0%B8%A5%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D-%E0%B9%80%E0%B8%8B%E0%B8%95-%E0%B8%AD%E0%B8%B1%E0%B8%A5%E0%B8%A1%E0%B8%AD%E0%B8%99%E0%B8%94%E0%B9%8C%E0%B8%9C%E0%B8%AA%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B9%87%E0%B8%94%E0%B8%A1%E0%B8%B0%E0%B8%A1%E0%B9%88%E0%B8%A7%E0%B8%87-i.304134090.7269177443",
    affiliateUrl: "https://s.shopee.co.th/BRe3srmlB",
  },
  {
    id: "body-care-set",
    title: "เซ็ตดูแลผิวและผม",
    icon: "🧴",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["female"],
    ageRange: [18, 55],
    occasions: ["birthday", "festival", "anniversary", "justbecause"],
    personality: ["homebody", "practical", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 800–2,500 บาท",
    currentPrice: "฿1,810",
    text: "ของใช้ได้จริงแต่ยังดูพิเศษ เลือกกลิ่นสะอาด ๆ จะให้ได้ง่ายกว่า",
    color: "#e8c8e8",
    imageUrl: "https://down-th.img.susercontent.com/file/th-11134207-81ztm-mop562k2a9e661_tn",
    researchUrl:
      "https://shopee.co.th/Kaff-Co.-Holiday-Set-1-2-Holiday-Hair-Skin-Care-%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D%E0%B9%81%E0%B8%AB%E0%B9%88%E0%B8%87%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B9%E0%B9%81%E0%B8%A5%E0%B8%84%E0%B8%A3%E0%B8%9A%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3-i.314209019.13156093664",
    affiliateUrl: "https://s.shopee.co.th/3B5FdQiAY1",
  },
  {
    id: "business-gift-set",
    title: "เซ็ตแก้วเก็บความร้อนและร่ม",
    icon: "☂️",
    recipients: ["coworker", "family"],
    genders: ["unisex"],
    ageRange: [22, 65],
    occasions: ["thankyou", "festival", "celebrate"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–900 บาท",
    currentPrice: "฿224",
    text: "ดูสุภาพ ใช้งานได้จริง เหมาะกับลูกค้า เพื่อนร่วมงาน หรือจับฉลากออฟฟิศ",
    color: "#abc9ff",
    imageUrl: "assets/product-images/business-gift-set.jpg",
    researchUrl:
      "https://shopee.co.th/%F0%9F%8E%81-Gift-Set-%E0%B9%80%E0%B8%8B%E0%B9%87%E0%B8%95%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%82%E0%B8%A7%E0%B8%B1%E0%B8%8D%E0%B8%98%E0%B8%B8%E0%B8%A3%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A2%E0%B8%B8%E0%B8%81%E0%B8%95%E0%B9%8C%E0%B9%83%E0%B8%8A%E0%B9%89-%E0%B9%81%E0%B8%81%E0%B9%89%E0%B8%A7%E0%B9%80%E0%B8%81%E0%B9%87%E0%B8%9A%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%99-%E0%B8%A3%E0%B9%88%E0%B8%A1-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%9E%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%87%E0%B8%B2%E0%B8%99-%E0%B8%A5%E0%B8%B9%E0%B8%81%E0%B8%84%E0%B9%89%E0%B8%B2-%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%9B%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B8%B1%E0%B8%A7-%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B9%80%E0%B8%81%E0%B8%B4%E0%B8%94-fan-i.877179409.56806485159",
    affiliateUrl: "https://s.shopee.co.th/1Vx1h8dbeK",
  },
  {
    id: "aroma-diffuser",
    title: "ดิฟฟิวเซอร์หรือเทียนหอม",
    icon: "🕯️",
    recipients: ["friend", "partner", "family", "self"],
    occasions: ["birthday", "thankyou", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium", "large"],
    price: "ประมาณ 250–1,800 บาท",
    text: "ช่วยให้ห้องน่าอยู่ขึ้น เหมาะกับคนรักบ้าน โต๊ะทำงาน หรือของขวัญขึ้นบ้านใหม่",
    color: "#ffb2c7",
    imageUrl: "",
    researchUrl: shopeeSearch("ดิฟฟิวเซอร์ เทียนหอม ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "board-game",
    title: "บอร์ดเกมเล่นง่าย",
    icon: "🎲",
    recipients: ["friend", "partner", "kid", "self"],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–1,500 บาท",
    text: "เหมาะกับคนชอบชวนเพื่อนเล่น เลือกเกมที่กติกาไม่ยากและเล่นซ้ำได้",
    color: "#ffce4d",
    imageUrl: "",
    researchUrl: shopeeSearch("บอร์ดเกม ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "wireless-earbuds",
    title: "หูฟังไร้สาย",
    icon: "🎧",
    recipients: ["friend", "partner", "family", "self"],
    occasions: ["birthday", "celebrate", "anniversary"],
    personality: ["tech", "active", "practical"],
    budget: ["medium", "large", "premium"],
    price: "ประมาณ 900–5,000 บาท",
    text: "ใช้ได้ทุกวันทั้งเดินทาง ทำงาน และออกกำลัง เป็นของที่คนรับนึกถึงบ่อย",
    color: "#b8c5ff",
    imageUrl: "",
    researchUrl: shopeeSearch("หูฟังไร้สาย ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "instant-camera",
    title: "กล้องอินสแตนท์หรือเครื่องพิมพ์รูป",
    icon: "📸",
    recipients: ["partner", "friend", "self"],
    occasions: ["birthday", "anniversary", "celebrate"],
    personality: ["creative", "active", "tech"],
    budget: ["large", "premium"],
    price: "ประมาณ 2,000–6,500 บาท",
    text: "เหมาะกับคนชอบถ่ายรูป เที่ยว และเก็บความทรงจำให้จับต้องได้",
    color: "#f4a8a1",
    imageUrl: "",
    researchUrl: shopeeSearch("กล้อง instant camera ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "travel-organizer",
    title: "กระเป๋าจัดระเบียบเดินทาง",
    icon: "🧳",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    occasions: ["birthday", "celebrate", "festival", "thankyou"],
    personality: ["active", "practical", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 200–1,200 บาท",
    text: "ของใช้จริงที่ช่วยชีวิตคนเดินทางบ่อย จัดสายชาร์จ เครื่องสำอาง หรือเสื้อผ้าได้",
    color: "#9fd9ef",
    imageUrl: "",
    researchUrl: shopeeSearch("กระเป๋าจัดระเบียบเดินทาง ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "plant-pot",
    title: "ต้นไม้ดูแลง่ายพร้อมกระถาง",
    icon: "🪴",
    recipients: ["friend", "family", "coworker", "self"],
    occasions: ["thankyou", "celebrate", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 150–900 บาท",
    text: "เหมาะกับโต๊ะทำงาน บ้านใหม่ หรือคนที่อยากเพิ่มสีเขียวแต่ไม่มีเวลาดูแลมาก",
    color: "#a9dfb3",
    imageUrl: "",
    researchUrl: shopeeSearch("ต้นไม้ดูแลง่าย กระถาง ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "baby-gift-set",
    title: "เซ็ตของขวัญเด็กแรกเกิด",
    icon: "🍼",
    recipients: ["kid", "family"],
    occasions: ["thankyou", "celebrate", "festival"],
    personality: ["practical"],
    budget: ["small", "medium", "large"],
    price: "ประมาณ 300–2,000 บาท",
    text: "ใช้ได้จริงและดูอบอุ่น เหมาะกับเยี่ยมคลอด รับขวัญหลาน หรือฝากครอบครัว",
    color: "#f8c986",
    imageUrl: "",
    researchUrl: shopeeSearch("เซ็ตของขวัญเด็กแรกเกิด"),
    affiliateUrl: "",
  },
  {
    id: "cookware",
    title: "เครื่องครัวชิ้นเก่ง",
    icon: "🍳",
    recipients: ["family", "friend", "partner", "self"],
    occasions: ["birthday", "celebrate", "thankyou", "anniversary"],
    personality: ["foodie", "practical", "homebody"],
    budget: ["medium", "large", "premium"],
    price: "ประมาณ 700–5,000 บาท",
    text: "เหมาะกับคนชอบทำอาหาร เลือกแบรนด์ดี ๆ แล้วเขาจะหยิบใช้ได้นาน",
    color: "#ffc6a5",
    imageUrl: "",
    researchUrl: shopeeSearch("เครื่องครัว ของขวัญ"),
    affiliateUrl: "",
  },
  {
    id: "mens-loafer-shoes",
    title: "รองเท้าโลฟเฟอร์ผู้ชาย",
    icon: "👞",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [20, 60],
    occasions: ["birthday", "anniversary", "celebrate", "justbecause"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–900 บาท",
    currentPrice: "฿488",
    text: "รองเท้าทรงสุภาพใส่ได้หลายโอกาส เหมาะกับผู้ชายที่ชอบของใช้จริงและแต่งตัวง่าย",
    color: "#d9c2a3",
    imageUrl: "assets/product-images/mens-loafer-shoes.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6L2HUJ8Fuf",
  },
  {
    id: "mens-bomber-jacket",
    title: "แจ็กเก็ตผู้ชายทรงคลาสสิก",
    icon: "🧥",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [18, 55],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["practical", "active"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–900 บาท",
    currentPrice: "฿432",
    text: "แจ็กเก็ตทรงเรียบใส่ง่าย เหมาะกับผู้ชายที่ชอบเสื้อผ้าใช้งานได้หลายสถานการณ์",
    color: "#2f3136",
    imageUrl: "assets/product-images/mens-bomber-jacket.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/40eMiAKeUU",
  },
  {
    id: "cheese-mini-gift",
    title: "กล่องของขวัญธีมชีสน่ารัก",
    icon: "🧀",
    recipients: ["friend", "kid", "coworker", "self"],
    genders: ["unisex"],
    ageRange: [8, 35],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small"],
    price: "ประมาณ 50–150 บาท",
    currentPrice: "฿69",
    text: "ของขวัญชิ้นเล็กหน้าตาน่ารัก เหมาะกับจับฉลาก เพื่อนสนิท หรือของแถมให้ดูใส่ใจ",
    color: "#ffce4d",
    imageUrl: "assets/product-images/cheese-mini-gift.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7fXf5A1T3T",
  },
  {
    id: "goose-plush-pillow",
    title: "ตุ๊กตาห่านกอดนุ่ม",
    icon: "🪿",
    recipients: ["partner", "friend", "kid", "self"],
    genders: ["female"],
    ageRange: [6, 35],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 90–300 บาท",
    currentPrice: "฿93",
    text: "ตุ๊กตากอดนุ่มชิ้นใหญ่ เหมาะกับคนชอบของน่ารัก แต่งห้อง หรือกอดนอน",
    color: "#f6e8c8",
    imageUrl: "assets/product-images/goose-plush-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJGaffoT",
  },
  {
    id: "custom-music-plaque-nfc",
    title: "กรอบเพลงพร้อมรูปและ NFC",
    icon: "🎵",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 45],
    occasions: ["anniversary", "birthday", "celebrate", "justbecause"],
    personality: ["creative", "homebody", "tech"],
    budget: ["medium"],
    price: "ประมาณ 600–1,200 บาท",
    currentPrice: "฿731",
    text: "ของขวัญสั่งทำที่ใส่รูป เพลง และข้อความส่วนตัว เหมาะกับวันครบรอบ งานแต่ง หรือคนพิเศษ",
    color: "#d8c0ff",
    imageUrl: "assets/product-images/custom-music-plaque-nfc.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4VadJYhsjT",
  },
  {
    id: "crochet-sunflower-bouquet",
    title: "ช่อดอกไม้ถักไหมพรม",
    icon: "🌻",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "celebrate", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–800 บาท",
    currentPrice: "฿357",
    text: "ช่อดอกไม้แฮนด์เมดที่เก็บได้นาน เหมาะกับวันเกิด วันครบรอบ หรือให้กำลังใจคนสำคัญ",
    color: "#ffce4d",
    imageUrl: "assets/product-images/crochet-sunflower-bouquet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4qDTiV1TYg",
  },
  {
    id: "mens-wallet-belt-gift-set",
    title: "เซ็ตกระเป๋าสตางค์และเข็มขัดผู้ชาย",
    icon: "👔",
    recipients: ["partner", "family", "friend", "coworker"],
    genders: ["male"],
    ageRange: [22, 65],
    occasions: ["birthday", "anniversary", "celebrate", "thankyou", "festival"],
    personality: ["practical"],
    budget: ["medium"],
    price: "ประมาณ 900–1,500 บาท",
    currentPrice: "฿1,028",
    text: "เซ็ตของใช้ผู้ชายที่ดูสุภาพและใช้งานได้จริง เหมาะกับแฟน คุณพ่อ ผู้ใหญ่ หรือโอกาสที่อยากให้ดูพรีเมียมขึ้น",
    color: "#303846",
    imageUrl: "assets/product-images/mens-wallet-belt-gift-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5VTAgAsqQs",
  },
  {
    id: "playboy-womens-watch-set",
    title: "เซ็ตนาฬิกาผู้หญิง PLAYBOY",
    icon: "⌚",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [18, 55],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["practical", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,430",
    text: "เซ็ตนาฬิกาพร้อมกล่องของขวัญ เหมาะกับแฟน เพื่อนสนิท หรือคนที่ชอบของใช้สวย ๆ ที่ใส่ได้จริง",
    color: "#e6c7c0",
    imageUrl: "assets/product-images/playboy-womens-watch-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7AbOfRdoMC",
  },
  {
    id: "duck-night-light",
    title: "โคมไฟกลางคืนรูปเป็ด",
    icon: "💡",
    recipients: ["kid", "friend", "partner", "self"],
    genders: ["unisex"],
    ageRange: [3, 35],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿154",
    text: "โคมไฟซิลิโคนแสงนุ่มสำหรับหัวเตียง เหมาะกับเด็ก คนชอบแต่งห้อง หรือของขวัญน่ารักงบไม่แรง",
    color: "#ffe88a",
    imageUrl: "assets/product-images/duck-night-light.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/110lKAiU8P",
  },
  {
    id: "aurora-gold-bracelet",
    title: "กำไลทองคำ AURORA",
    icon: "💛",
    recipients: ["partner", "family", "self"],
    genders: ["female"],
    ageRange: [22, 75],
    occasions: ["anniversary", "birthday", "celebrate", "thankyou"],
    personality: ["practical", "creative"],
    budget: ["premium"],
    price: "ประมาณ 3,000 บาทขึ้นไป",
    currentPrice: "฿3,990",
    text: "ของขวัญมูลค่าสูงที่เก็บได้นาน เหมาะกับแฟน ผู้ใหญ่ หรือโอกาสสำคัญที่ต้องการความพรีเมียม",
    color: "#f5d36b",
    imageUrl: "assets/product-images/aurora-gold-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/70HyTQeSgb",
  },
  {
    id: "birthday-candle-jewelry-box",
    title: "กล่องของขวัญเทียนเค้กและเครื่องประดับ",
    icon: "🎂",
    recipients: ["partner", "friend", "self"],
    genders: ["female"],
    ageRange: [14, 40],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 200–500 บาท",
    currentPrice: "฿240",
    text: "กล่องของขวัญหน้าตาน่ารักพร้อมกลิ่นอายวันเกิด เหมาะกับแฟน เพื่อนสนิท หรือคนที่ชอบของกุ๊กกิ๊ก",
    color: "#ffd0df",
    imageUrl: "assets/product-images/birthday-candle-jewelry-box.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/AAF0FK591O",
  },
  {
    id: "moomin-plush-pillow",
    title: "ตุ๊กตามูมินกอดนุ่ม",
    icon: "🤍",
    recipients: ["partner", "friend", "kid", "self"],
    genders: ["female", "unisex"],
    ageRange: [6, 40],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–900 บาท",
    currentPrice: "฿490 - ฿790",
    text: "ตุ๊กตาคาแรกเตอร์นุ่ม ๆ สำหรับกอดหรือแต่งห้อง เหมาะกับคนชอบของน่ารักและของขวัญอบอุ่น",
    color: "#d8ecff",
    imageUrl: "assets/product-images/moomin-plush-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6L2HgRNoHY",
  },
  {
    id: "liverpool-man-u-mug",
    title: "แก้วฟุตบอล Liverpool 7-0 Man U",
    icon: "⚽",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 60],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["homebody", "active", "creative"],
    budget: ["small"],
    price: "ประมาณ 100–250 บาท",
    currentPrice: "฿162",
    text: "แก้วลายฟุตบอลสำหรับแฟนบอล เหมาะกับเพื่อนสนิท เพื่อนร่วมงาน หรือคนที่อินโมเมนต์ทีมโปรด",
    color: "#dce8f4",
    imageUrl: "assets/product-images/liverpool-man-u-mug.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8pjcf8yCHp",
  },
  {
    id: "shy-boy-table-lamp",
    title: "โคมไฟตั้งโต๊ะ Shy Boy",
    icon: "🛋️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["unisex"],
    ageRange: [12, 55],
    occasions: ["birthday", "festival", "justbecause", "thankyou"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–700 บาท",
    currentPrice: "฿283",
    text: "โคมไฟตั้งโต๊ะดีไซน์น่ารักสำหรับแต่งห้องหรือโต๊ะทำงาน เหมาะกับคนอยู่บ้านและสายของแต่งห้อง",
    color: "#f0dfc8",
    imageUrl: "assets/product-images/shy-boy-table-lamp.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EAC1Mi8",
  },
  {
    id: "menspe-crossbody-bag",
    title: "กระเป๋าสะพายข้างผู้ชาย MENSPE",
    icon: "🎒",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["practical", "active", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–600 บาท",
    currentPrice: "฿290",
    text: "กระเป๋าสะพายข้างทรงเรียบ ใช้ได้ทุกวัน เหมาะกับผู้ชายที่ชอบของ practical และพกของจำเป็นน้อยชิ้น",
    color: "#1f2329",
    imageUrl: "assets/product-images/menspe-crossbody-bag.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9AMT58t3VA",
  },
  {
    id: "civago-lucky-puppy-tumbler",
    title: "แก้วน้ำ CIVAGO x Lucky Puppy",
    icon: "🥤",
    recipients: ["friend", "partner", "coworker", "kid", "self"],
    genders: ["female", "unisex"],
    ageRange: [10, 45],
    occasions: ["birthday", "festival", "justbecause", "thankyou"],
    personality: ["practical", "homebody", "creative"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–600 บาท",
    currentPrice: "฿399",
    text: "แก้วน้ำลายคาแรกเตอร์น่ารัก ใช้งานได้ทุกวัน เหมาะกับคนทำงาน นักเรียน หรือคนชอบของพกพาสวย ๆ",
    color: "#d6c0aa",
    imageUrl: "assets/product-images/civago-lucky-puppy-tumbler.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EAOljX6",
  },
  {
    id: "eloop-magsafe-powerbank",
    title: "พาวเวอร์แบงก์ Eloop MagCharge",
    icon: "🔋",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [14, 65],
    occasions: ["birthday", "festival", "celebrate", "thankyou", "justbecause"],
    personality: ["tech", "active", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–1,000 บาท",
    currentPrice: "฿428",
    text: "พาวเวอร์แบงก์ชาร์จเร็วสำหรับคนใช้มือถือหนัก เดินทางบ่อย หรือชอบแกดเจ็ตที่ใช้งานได้จริง",
    color: "#5d636b",
    imageUrl: "assets/product-images/eloop-magsafe-powerbank.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6pyYJ2kRRw",
  },
  {
    id: "samurai-umbrella",
    title: "ร่มด้ามดาบซามูไร",
    icon: "☂️",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "active", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–700 บาท",
    currentPrice: "฿456",
    text: "ร่มดีไซน์ดาบซามูไรสำหรับคนชอบอนิเมะหรือของไม่เหมือนใคร เป็นของใช้จริงที่มีคาแรกเตอร์ชัด",
    color: "#2d3038",
    imageUrl: "assets/product-images/samurai-umbrella.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/gNuxp8wKp",
  },
  {
    id: "instax-mini-evo-camera",
    title: "กล้อง Fujifilm Instax Mini Evo",
    icon: "📸",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 55],
    occasions: ["birthday", "anniversary", "celebrate"],
    personality: ["creative", "tech", "active"],
    budget: ["premium"],
    price: "ประมาณ 5,000 บาทขึ้นไป",
    currentPrice: "฿6,536",
    text: "กล้อง instant hybrid สำหรับคนชอบถ่ายรูปและเก็บโมเมนต์ เหมาะกับของขวัญชิ้นใหญ่ในโอกาสสำคัญ",
    color: "#d6c2a8",
    imageUrl: "assets/product-images/instax-mini-evo-camera.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJUFswcd",
  },
  {
    id: "aroma-humidifier",
    title: "เครื่องพ่นน้ำหอมอโรม่า",
    icon: "🌫️",
    recipients: ["friend", "partner", "family", "coworker", "self"],
    genders: ["unisex"],
    ageRange: [18, 65],
    occasions: ["birthday", "thankyou", "festival", "justbecause"],
    personality: ["homebody", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 300–700 บาท",
    currentPrice: "฿377",
    text: "เครื่องพ่นอโรม่าสำหรับห้องนอนหรือโต๊ะทำงาน เหมาะกับคนอยู่บ้าน รักความสบาย หรืออยากให้พื้นที่ผ่อนคลายขึ้น",
    color: "#dfe8dc",
    imageUrl: "assets/product-images/aroma-humidifier.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/gNuyYCgyI",
  },
  {
    id: "portable-mini-projector",
    title: "โปรเจกเตอร์พกพา",
    icon: "📽️",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["tech", "homebody", "creative"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,357",
    text: "โปรเจกเตอร์ขนาดเล็กสำหรับดูหนัง เล่นเกม หรือจัดมุมพักผ่อนในห้อง เหมาะกับสายเทคและคนชอบอยู่บ้าน",
    color: "#d9ecff",
    imageUrl: "assets/product-images/portable-mini-projector.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/8V6mJACokr",
  },
  {
    id: "kai-hair-clipper",
    title: "ปัตตาเลี่ยนไฟฟ้า KAI",
    icon: "✂️",
    recipients: ["partner", "family", "friend", "self"],
    genders: ["male"],
    ageRange: [18, 65],
    occasions: ["birthday", "festival", "thankyou", "justbecause"],
    personality: ["practical", "tech"],
    budget: ["medium", "large"],
    price: "ประมาณ 1,000–2,000 บาท",
    currentPrice: "฿1,689",
    text: "เครื่องตัดผมไฟฟ้าสำหรับคนที่ชอบดูแลตัวเองหรืออยากมีอุปกรณ์ใช้เองที่บ้าน เหมาะกับของขวัญผู้ชายสาย practical",
    color: "#2d2d2d",
    imageUrl: "assets/product-images/kai-hair-clipper.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9UzJVFkscL",
  },
  {
    id: "twilight-library-diy-book-nook",
    title: "ชุด DIY บ้านหนังสือจิ๋ว Twilight Library",
    icon: "📚",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["unisex"],
    ageRange: [12, 60],
    occasions: ["birthday", "festival", "justbecause", "celebrate"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–800 บาท",
    currentPrice: "฿438",
    text: "ชุดประกอบบ้านหนังสือจิ๋วพร้อมไฟ LED เหมาะกับคนรักหนังสือ งานคราฟต์ และของแต่งห้องที่มีเรื่องราว",
    color: "#8b5a3c",
    imageUrl: "assets/product-images/twilight-library-diy-book-nook.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/9fIjhg8VHc",
  },
  {
    id: "enchen-shaver-gift-set",
    title: "เซ็ตเครื่องโกนหนวด Enchen",
    icon: "🪒",
    recipients: ["partner", "family", "friend", "self"],
    genders: ["male"],
    ageRange: [18, 70],
    occasions: ["birthday", "festival", "thankyou", "justbecause"],
    personality: ["practical", "tech"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–900 บาท",
    currentPrice: "฿461",
    text: "ชุดเครื่องโกนหนวดและอุปกรณ์ดูแลตัวเองสำหรับผู้ชาย เหมาะกับของขวัญที่ใช้งานได้จริงทุกวัน",
    color: "#17191d",
    imageUrl: "assets/product-images/enchen-shaver-gift-set.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/2LW8yILgyA",
  },
  {
    id: "thai-funny-tshirt",
    title: "เสื้อยืดลายไทยสายฮา",
    icon: "👕",
    recipients: ["friend", "partner", "coworker", "self"],
    genders: ["male", "unisex"],
    ageRange: [13, 45],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody"],
    budget: ["small", "medium"],
    price: "ประมาณ 250–500 บาท",
    currentPrice: "฿323",
    text: "เสื้อยืดลายขำ ๆ สำหรับเพื่อนหรือคนที่ชอบมุกไทย ใส่เป็นของขวัญสนุก ๆ ได้ดี",
    color: "#f47b25",
    imageUrl: "assets/product-images/thai-funny-tshirt.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6ff88Spllx",
  },
  {
    id: "enter-key-stress-pillow",
    title: "หมอนปุ่ม Enter แก้เครียด",
    icon: "⌨️",
    recipients: ["friend", "coworker", "partner", "self"],
    genders: ["unisex"],
    ageRange: [12, 55],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["creative", "homebody", "practical", "tech"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿159",
    text: "หมอนปุ่ม Enter ขนาดใหญ่สำหรับกดระบายอารมณ์ เหมาะกับเพื่อนร่วมงาน คนทำงานหน้าคอม หรือของขวัญสายฮา",
    color: "#111111",
    imageUrl: "assets/product-images/enter-key-stress-pillow.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/6VLhwG7Mn3",
  },
  {
    id: "hello-kitty-ceramic-cup",
    title: "แก้วเซรามิก Hello Kitty",
    icon: "🎀",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["female"],
    ageRange: [10, 45],
    occasions: ["birthday", "anniversary", "festival", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 400–700 บาท",
    currentPrice: "฿458",
    text: "แก้วเซรามิกคาแรกเตอร์พร้อมแพ็กเกจของขวัญ เหมาะกับคนชอบ Hello Kitty หรือของใช้ที่น่ารักเป็นพิเศษ",
    color: "#ef3f3f",
    imageUrl: "assets/product-images/hello-kitty-ceramic-cup.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4VadYzY1uk",
  },
  {
    id: "personalized-steel-bracelet",
    title: "กำไลข้อมือสแตนเลสสลักชื่อ",
    icon: "🔗",
    recipients: ["partner", "friend", "self"],
    genders: ["unisex"],
    ageRange: [14, 45],
    occasions: ["anniversary", "birthday", "festival", "justbecause"],
    personality: ["creative", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿139",
    text: "กำไลข้อมือสลักชื่อหรือข้อความส่วนตัว เหมาะกับของขวัญคู่ วาเลนไทน์ วันเกิด หรือของแทนใจงบเบา",
    color: "#1f1f1f",
    imageUrl: "assets/product-images/personalized-steel-bracelet.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/Ll52daPqv",
  },
  {
    id: "huawei-watch-fit-5",
    title: "HUAWEI WATCH FIT 5",
    icon: "⌚",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["unisex"],
    ageRange: [16, 65],
    occasions: ["birthday", "anniversary", "celebrate", "festival"],
    personality: ["tech", "active", "practical"],
    budget: ["premium"],
    price: "ประมาณ 3,000 บาทขึ้นไป",
    currentPrice: "฿3,710",
    text: "สมาร์ทวอทช์สำหรับดูแลสุขภาพ ออกกำลัง และใช้งานประจำวัน เหมาะกับสายเทคหรือคนที่อยากดูแลตัวเองจริงจัง",
    color: "#dbe0e6",
    imageUrl: "assets/product-images/huawei-watch-fit-5.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/5VTBCHSmlI",
  },
  {
    id: "gq-running-shorts",
    title: "กางเกงวิ่ง GQ Everyday",
    icon: "🏃",
    recipients: ["partner", "friend", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [14, 55],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["active", "practical"],
    budget: ["small"],
    price: "ประมาณ 100–300 บาท",
    currentPrice: "฿155",
    text: "กางเกงขาสั้นสำหรับวิ่งหรือออกกำลัง ใส่ได้ทุกวัน เหมาะกับคนรักสุขภาพหรือคนที่ชอบของใช้จริง",
    color: "#6b7c68",
    imageUrl: "assets/product-images/gq-running-shorts.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/7pr5yhZACX",
  },
  {
    id: "iron-man-arc-reactor-lamp",
    title: "แท่นชาร์จ MagSafe Arc Reactor Iron Man",
    icon: "🦾",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "unisex"],
    ageRange: [12, 45],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["tech", "practical", "creative"],
    budget: ["medium"],
    price: "ประมาณ 900-1,200 บาท",
    currentPrice: "฿947",
    text: "แท่นชาร์จมือถือแบบ MagSafe/ไร้สายธีม Arc Reactor Iron Man เหมาะกับแฟน Marvel คนชอบแกดเจ็ต หรือคนที่อยากได้ของใช้บนโต๊ะทำงานที่มีคาแรกเตอร์",
    color: "#2f3b4a",
    imageUrl: "assets/product-images/iron-man-arc-reactor-lamp.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/18EeOHbKf",
  },
  {
    id: "scented-candle-gift-box",
    title: "Gift Box เทียนหอม 3 กลิ่น",
    icon: "🕯️",
    recipients: ["friend", "partner", "coworker", "family", "self"],
    genders: ["female", "unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "celebrate", "justbecause"],
    personality: ["homebody", "creative", "practical"],
    budget: ["small", "medium"],
    price: "ประมาณ 300-500 บาท",
    currentPrice: "฿333",
    text: "กล่องของขวัญเทียนหอม 3 กลิ่นพร้อมแพ็กเกจผูกโบว์ เหมาะกับวันเกิด ปีใหม่ ของขอบคุณ หรือคนที่ชอบบรรยากาศห้องหอม ๆ",
    color: "#b56a4d",
    imageUrl: "assets/product-images/scented-candle-gift-box.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/4AxncWKxa6",
  },
  {
    id: "soft-kettlebell",
    title: "เคตเทิลเบลล์แบบนุ่ม",
    icon: "🏋️",
    recipients: ["friend", "partner", "family", "self"],
    genders: ["male", "female", "unisex"],
    ageRange: [16, 60],
    occasions: ["birthday", "festival", "justbecause"],
    personality: ["active", "practical"],
    budget: ["small"],
    price: "ประมาณ 150-400 บาท",
    currentPrice: "฿170",
    text: "เคตเทิลเบลล์แบบนุ่มสำหรับออกกำลังกายที่บ้าน เหมาะกับคนรักสุขภาพ มือใหม่ฟิตเนส หรือคนที่อยากเริ่มขยับตัวแบบจริงจัง",
    color: "#4a4a4a",
    imageUrl: "assets/product-images/soft-kettlebell.jpg",
    researchUrl: "",
    affiliateUrl: "https://s.shopee.co.th/1LdcFZLZT3",
  },
];
